language: python
python:
    - "2.7"
sudo: required
install:
    - pip install -r requirements.txt
    - pip install coveralls
    - pip install codecov
script:
    - nosetests --with-coverage
after_success:
    - coveralls
    - codecov
notifications:
    email: false